services:
  - type: web
    name: ux-audit-crew
    env: python
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: FIGMA_ACCESS_TOKEN
        sync: false
      - key: PYTHON_VERSION
        value: 3.7.0
    healthCheckPath: /
    autoDeploy: true
    plan: free 