services:
  - type: web
    name: ux-audit-crew
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: FIGMA_ACCESS_TOKEN
        sync: false
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 10000 